"""Add advanced stats to Player

Revision ID: 2cdc3d9fe2c3
Revises: 1a08bed3318a
Create Date: 2025-06-29 01:55:06.499958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdc3d9fe2c3'
down_revision = '1a08bed3318a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minutes_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('yellow_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_cards', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('injured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('injured')
        batch_op.drop_column('rating')
        batch_op.drop_column('red_cards')
        batch_op.drop_column('yellow_cards')
        batch_op.drop_column('minutes_played')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
