"""Add year_created and trophies to Team

Revision ID: ec4348a3a60b
Revises: 2cdc3d9fe2c3
Create Date: 2025-06-29 03:12:52.925656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4348a3a60b'
down_revision = '2cdc3d9fe2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_created', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trophies', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('trophies')
        batch_op.drop_column('year_created')

    # ### end Alembic commands ###
